apiVersion: capa-automation/v1
kind: ClusterAutomationSpec
metadata:
  name: control-plane-upgrade
spec:
  action: apply
  cluster: ""       # Set via --cluster
  namespace: ns-rosa-hcp
  actions:
    - feature: control_plane_upgrade
      value: ""     # Set via -e version=4.20.12
      wait: true
