# Feature: Private Network
# Applies to: create (immutable after creation)
apiVersion: capa-automation/v1
kind: ClusterAutomationSpec
metadata:
  name: private-network
spec:
  action: create
  cluster: ''
  namespace: ns-rosa-hcp
  features:
    private_network: false
